=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/Ejemplo03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="desayunos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="comida" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="nombre" type="xs:string"></xs:element>
                    <xs:element name="precio" type="xs:string"></xs:element>
                    <xs:element name="descripcion" type="xs:string"></xs:element>
                    <xs:element name="calorias" type="xs:string"></xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
    </xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/Ejemplo01.xml
<?xml version="1.0" encoding="UTF-8"?>
<desayunos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="Ejemplo03.xsd">
    <comida>
        <nombre>Belgian Waffles</nombre>
        <precio>$5.95</precio>
        <descripcion>Two of our famous Belgian Waffles with plenty of real maple syrup</descripcion>
        <calorias>650</calorias>
    </comida>
    <comida>
        <nombre>Strawberry Belgian Waffles</nombre>
        <precio>$7.95</precio>
        <descripcion>Light Belgian waffles covered with strawberries and whipped cream</descripcion>
        <calorias>900</calorias>
    </comida>
    <comida>
        <nombre>Berry-Berry Belgian Waffles</nombre>
        <precio>$8.95</precio>
        <descripcion>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</descripcion>
        <calorias>900</calorias>
    </comida>
    <comida>
        <nombre>French Toast</nombre>
        <precio>$4.50</precio>
        <descripcion>Thick slices made from our homemade sourdough bread</descripcion>
        <calorias>600</calorias>
    </comida>
    <comida>
        <nombre>Homestyle Breakfast</nombre>
        <precio>$6.95</precio>
        <descripcion>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</descripcion>
        <calorias>950</calorias>
    </comida>
</desayunos>
