=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioTRECE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="listado" type="tListado"/>
    <xs:complexType name="tListado">
        <xs:sequence>
            <xs:element name="afiliado" type="tAfiliado" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tAfiliado">
        <xs:sequence>
            <xs:choice>
                <xs:element name="DNI" type="xs:string"/>
                <xs:element name="NIE" type="xs:string"/>
            </xs:choice>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="situacion_laboral" type="tLaboral"/>
            <xs:element name="fecha_nacimiento" type="tFecha"/>
            <xs:element name="listado_bajas" type="tLBajas" minOccurs="0"/>
            <xs:element name="listado_prestaciones" type="tLPrestaciones"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tLBajas">
        <xs:sequence>
            <xs:element name="baja" type="tBaja" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tBaja">
        <xs:sequence>
            <xs:element name="causa" type="xs:string"/>
            <xs:element name="fecha_inicio" type="tFecha"/>
            <xs:element name="fecha_final" type="tFecha" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tLPrestaciones">
        <xs:sequence>
            <xs:element name="prestacion" type="tPrestacion" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tPrestacion">
        <xs:sequence>
            <xs:element name="cantidad" type="xs:float"/>
            <xs:element name="inicio" type="tFecha"/>
            <xs:element name="final" type="tFecha" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tLaboral">
        <xs:restriction base="xs:string">
            <xs:enumeration value="en_paro"/>
            <xs:enumeration value="en_activo"/>
            <xs:enumeration value="jubilado"/>
            <xs:enumeration value="edad_no_laboral"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="tFecha">
        <xs:sequence>
            <xs:element name="dia" type="xs:int"/>
            <xs:element name="mes" type="xs:int"/>
            <xs:element name="aÃ±o" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioTRECE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="EjercicioTRECE.xsd">

    <afiliado>
        <DNI>39497088Q</DNI>
        <nombre>Pepe</nombre>
        <apellidos>Perez</apellidos>
        <situacion_laboral>en_activo</situacion_laboral>
        <fecha_nacimiento>
            <dia>12</dia>
            <mes>2</mes>
            <año>1998</año>
        </fecha_nacimiento>
        <listado_bajas></listado_bajas>
        <listado_prestaciones>
            <prestacion>
                <cantidad>1564.34</cantidad>
                <inicio>
                    <dia>13</dia>
                    <mes>5</mes>
                    <año>1999</año>
                </inicio>
                <final>
                    <dia>21</dia>
                    <mes>6</mes>
                    <año>1999</año>
                </final>
            </prestacion>
        </listado_prestaciones>
    </afiliado>
    <afiliado>
        <NIE>X12564782</NIE>
        <nombre>Callum</nombre>
        <apellidos>Jones</apellidos>
        <situacion_laboral>en_paro</situacion_laboral>
        <fecha_nacimiento>
            <dia>15</dia>
            <mes>11</mes>
            <año>1997</año>
        </fecha_nacimiento>
        <listado_bajas>
            <baja>
                <causa>amigdalitis</causa>
                <fecha_inicio>
                    <dia>15</dia>
                    <mes>7</mes>
                    <año>2022</año>
                </fecha_inicio>
                <fecha_final>
                    <dia>22</dia>
                    <mes>7</mes>
                    <año>2022</año>
                </fecha_final>
            </baja>
        </listado_bajas>
        <listado_prestaciones>
            <prestacion>
                <cantidad>234</cantidad>
                <inicio>
                    <dia>23</dia>
                    <mes>4</mes>
                    <año>2002</año>
                </inicio>
                <final>
                    <dia>01</dia>
                    <mes>6</mes>
                    <año>2003</año>
                </final>
            </prestacion>
        </listado_prestaciones>
    </afiliado>
</listado>
