=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioNUEVE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:esq="http://www.w3.org/2001/XMLSchema">

    <xs:element name="operacion" type="tOperacion"/>
    <xs:complexType name="tOperacion">
        <xs:sequence>
            <xs:element name="entrega" type="tEntrega"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="tEntrega">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="lote" type="Tlote"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Tlote">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="pale" type="tPale"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tPale">
        <xs:sequence>
            <xs:element name="numcajas" type="xs:int"/>
            <xs:element name="contenido" type="tContenido"/>
            <xs:element name="peso" type="xs:string"/>
            <xs:element name="formamanipulacion" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tContenido">
        <xs:sequence>
            <xs:element name="nombrecomponente" type="xs:string"/>
                <xs:element name="procedencia" type="tProcedencia" minOccurs="0"/>
            <xs:element name="numserie" type="xs:string"/>
            <xs:element name="peso" type="xs:string"/>
            <xs:element name="unidades" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tProcedencia">
        <xs:sequence>
            <xs:element name="pais" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioNUEVE.xml
<?xml version="1.0" encoding="UTF-8"?>
<operacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="EjercicioNUEVE.xsd">
<entrega>
    <lote>
        <pale>
            <numcajas>3</numcajas>
            <contenido>
                <nombrecomponente>Fuentes</nombrecomponente>
                <numserie>3A</numserie>
                <peso>2kg</peso>
                <unidades>50</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
    <lote>
        <pale>
            <numcajas>2</numcajas>
            <contenido>
                <nombrecomponente>CPUs</nombrecomponente>
                <procedencia>
                    <pais>China</pais>
                    <pais>Corea del Sur</pais>
                </procedencia>
                <numserie>5B</numserie>
                <peso>100g</peso>
                <unidades>1000</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
</entrega>
</operacion>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioNUEVE.xml
<?xml version="1.0" encoding="UTF-8"?>
<entrega xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ejercicioNUEVE.xsd">
    <lote>
        <pale>
            <numcajas>3</numcajas>
            <contenido>
                <nombrecomponente>Fuentes</nombrecomponente>
                <numserie>3A</numserie>
                <pesounidad>2kg</pesounidad>
                <unidades>50</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
    <lote>
        <pale>
            <numcajas>2</numcajas>
            <contenido>
                <nombrecomponente>CPUs</nombrecomponente>
                <procedencia>
                    <pais>China</pais>
                    <pais>Corea del Sur</pais>
                </procedencia>
                <numserie>5B</numserie>
                <pesounidad>100g</pesounidad>
                <unidades>1000</unidades>
            </contenido>
            <peso>100kg</peso>
            <formamanipulacion>Manual</formamanipulacion>
        </pale>
    </lote>
</entrega>
