=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioONCE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pedido" type="tPedido"/>

    <xs:complexType name="tPedido">
        <xs:sequence>
            <xs:element name="tractor" type="tTractor" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tTractor">
        <xs:sequence>
            <xs:element name="componente" type="tComponente" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tComponente">
        <xs:sequence>
            <xs:element name="fechaentrega" type="tFechaentrega" minOccurs="0"/>
            <xs:choice>
                <xs:element name="fragil" type="tFragil"/>
                <xs:element name="nofragil" type="tNofragil"/>
            </xs:choice>
            <xs:element name="peso" type="tPeso"/>
            <xs:element name="numserie" type="xs:string"/>
            <xs:element name="kmmaximos" type="xs:int" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="nombrefabricante" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="tPeso">
        <xs:simpleContent>
            <xs:extension base="xs:int">
                <xs:attribute name="unidad" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="tFechaentrega">
        <xs:sequence>
            <xs:element name="dia" type="xs:int" minOccurs="0"/>
            <xs:element name="mes" type="xs:int"/>
            <xs:element name="anio" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tFragil">
    </xs:complexType>

    <xs:complexType name="tNofragil">
    </xs:complexType>
</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/EjercicioONCE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="EjercicioONCE.xsd">
    <tractor>
        <componente nombrefabricante="Ebro">
            <fechaentrega>
                <mes>2018</mes> <anio>2018</anio>
            </fechaentrega>
            <fragil/>
            <peso unidad="kg">12</peso>
            <numserie>00A</numserie>
        </componente>
        <componente nombrefabricante="Avia">
            <fechaentrega>
                <dia>12</dia><mes>1</mes><anio>2019</anio>
            </fechaentrega>
            <nofragil/>
            <peso unidad="g">1450</peso>
            <numserie>00D</numserie>
            <kmmaximos>25000</kmmaximos>
        </componente>
    </tractor>
    <tractor>
        <componente nombrefabricante="John Deere">
            <fragil/>
            <peso unidad="g">770</peso>
            <numserie>43Z</numserie>
        </componente>
    </tractor>
</pedido>
