=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/ejercicioDOS.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="listapedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numeroSerie" type="xs:long"/>
                            <xs:element name="cantidad" type="xs:int"/>
                            <xs:element name="peso" minOccurs="0" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/BSintroduccion/Galeria/Imagenes/Tercera_Evaluacion/ejercicioDOS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listapedidos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
             xs:noNamespaceSchemaLocation="ejercicioDOS.xsd">
    <pedido>
        <numeroSerie>54</numeroSerie>
        <cantidad>7</cantidad>
        <peso>8976</peso>
    </pedido>
    <pedido>
        <numeroSerie>765</numeroSerie>
        <cantidad>089</cantidad>
        <peso>68</peso>
    </pedido>
    <pedido>
    <numeroSerie>123</numeroSerie>
    <cantidad>543</cantidad>
    <peso>6</peso>
</pedido>
</listapedidos>
