=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioDOS.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listapedidos">
        <xs:complexType>
                <xs:element name="pedido"/>
            <
                 <xs:sequence>
                <xs:element name="importe" type="xs:long"/>
                <xs:element name="direccion" type="xs:string"/>
                <xs:element name="cliente" type="xs:string"/>
                <xs:element name="cod" type="xs:string"/>
                 </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioDOS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listapedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ejercicioDOS.xsd">
    <pedido>
        <cliente>Juan</cliente>
        <importe>100</importe>
        <direccion>Madrid</direccion>
        <cod>127F</cod>
    </pedido>
    <pedido>
        <cliente>Lucas</cliente>
        <importe>346</importe>
        <direccion>Barcerlona</direccion>
        <cod>272Q</cod>
    </pedido>
    <pedido>
        <cliente>Ana</cliente>
        <importe>51</importe>
        <direccion>Valencia</direccion>
        <cod>KKW</cod>
    </pedido>
</listapedidos>
