=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioSIETE.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--raÃ­z de documentos-->
    <xs:element name="listafacturas" type="tipoLista"/>

    <!--Las facturas tienen un atributo opcional fecha-->
    <xs:complexType name="tipoLista">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="factura" type="tipoFactura"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoFactura">
        <xs:sequence>
            <xs:element name="emisor" type="tipoRepetido"/>
            <xs:element name="pagador" type="tipoRepetido"/>
            <xs:element name="importe" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="fecha" type="xs:date" use="required"/>
    </xs:complexType>

    <!--el emisor y el pagador tienen un atributo cif-->
    <xs:complexType name="tipoRepetido">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="volumen" minOccurs="0" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="cif" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioSIETE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listafacturas  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="ejercicioSIETE.xsd">

    <factura fecha="2008-09-29">
        <emisor cif="123456B">
            <nombre>string</nombre>
            <volumen>1.5E2</volumen>
        </emisor>
        <pagador cif="985764C">
            <nombre>string</nombre>
            <volumen>1.5E2</volumen>
        </pagador>
        <importe>1.5E2</importe>
    </factura>
    <factura fecha="2012-09-29">
        <emisor cif="123456Q">
            <nombre>string</nombre>
            <volumen>1.5E2</volumen>
        </emisor>
        <pagador cif="985764X">
            <nombre>string</nombre>
        </pagador>
        <importe>1.5E2</importe>
    </factura>
</listafacturas>
