=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioTRECE.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listado" type="tListado"/>
    <xsd:complexType name="tListado">
        <xsd:sequence>
            <xsd:element name="afiliado" type="tAfiliado" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tAfiliado">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="DNI" type="xsd:string"/>
                <xsd:element name="NIE" type="xsd:string"/>
            </xsd:choice>
            <xsd:element name="Nombre" type="xsd:string"/>
            <xsd:element name="Apellidos" type="xsd:string"/>
            <xsd:element name="situacion_laboral" type="tLaboral"/>
            <xsd:element name="fecha_nacimiento" type="tFecha"/>
            <xsd:element name="listado_bajas" type="tLBajas"/>
            <xsd:element name="listado_prestaciones" type="tLPrestaciones"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tLPrestaciones">
        <xsd:sequence>
            <xsd:element name="prestacion" type="tPrestacion" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tPrestacion">
        <xsd:sequence>
            <xsd:element name="cantidad" type="xsd:float"/>
            <xsd:element name="inicio" type="tFecha"/>
            <xsd:element name="final" type="tFecha"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="tLaboral">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="en_paro"/>
            <xsd:enumeration value="en_activo"/>
            <xsd:enumeration value="jubilado"/>
            <xsd:enumeration value="edad_no_laboral"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="tFecha">
        <xsd:sequence>
            <xsd:element name="dia" type="xsd:int"/>
            <xsd:element name="mes" type="xsd:int"/>
            <xsd:element name="aÃ±o" type="xsd:int"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tLBajas">
        <xsd:sequence>
            <xsd:element name="baja" type="tBaja" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="tBaja">
        <xsd:sequence>
            <xsd:element name="causa" type="xsd:string"/>
            <xsd:element name="fecha_inicio" type="tFecha"/>
            <xsd:element name="fecha_final" type="tFecha" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== gabrielvzqz/Marcas-1-/Tercer Trimestre/XML/ejercicioTRECE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listado xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ejercicioTRECE.xsd">
    <afiliado>
        <DNI>385786787</DNI>
        <Nombre>Pepe</Nombre>
        <Apellidos>Domingeuz Arieta</Apellidos>
        <situacion_laboral>en_paro</situacion_laboral>
        <fecha_nacimiento>
            <dia>12</dia>
            <mes>2</mes>
            <año>1988</año>
        </fecha_nacimiento>
        <listado_bajas></listado_bajas>
        <listado_prestaciones>
            <prestacion>
                <cantidad>1564.34</cantidad>
                <inicio>
                    <dia>01</dia>
                    <mes>01</mes>
                    <año>1999</año>
                </inicio>
                <final>
                    <dia>05</dia>
                    <mes>07</mes>
                    <año>2008</año>
                </final>
            </prestacion>
        </listado_prestaciones>
    </afiliado>
    <afiliado>
        <DNI>X35490957</DNI>
        <Nombre>Mohamed</Nombre>
        <Apellidos>Avdol</Apellidos>
        <situacion_laboral>en_paro</situacion_laboral>
        <fecha_nacimiento>
            <dia>12</dia>
            <mes>2</mes>
            <año>1988</año>
        </fecha_nacimiento>
        <listado_bajas>
            <baja>
                <causa>amigdalitis</causa>
                <fecha_inicio>
                    <dia>01</dia>
                    <mes>01</mes>
                    <año>2003</año>
                </fecha_inicio>
                <fecha_final>
                    <dia>15</dia>
                    <mes>12</mes>
                    <año>2022</año>
                </fecha_final>
            </baja>
        </listado_bajas>
        <listado_prestaciones></listado_prestaciones>
    </afiliado>
</listado>
